module com.mynetpcb.core {
	exports com.mynetpcb.core.capi;
	exports com.mynetpcb.core.capi.credentials;
    exports com.mynetpcb.core.capi.clipboard;
	exports com.mynetpcb.core.capi.container;
	exports com.mynetpcb.core.capi.shape;
	exports com.mynetpcb.core.capi.component;
	exports com.mynetpcb.core.utils;
	exports com.mynetpcb.core.capi.print;
	exports com.mynetpcb.core.capi.unit;
	exports com.mynetpcb.core.capi.config;
	exports com.mynetpcb.core.capi.event;
	exports com.mynetpcb.core.capi.gerber;
	exports com.mynetpcb.core.capi.flyweight;
	exports com.mynetpcb.core.capi.gui;
	exports com.mynetpcb.core.capi.gui.button;
	exports com.mynetpcb.core.capi.gui.panel;
	exports com.mynetpcb.core.capi.gui.filter;
	exports com.mynetpcb.core.capi.gui.searchcombo;
	exports com.mynetpcb.core.capi.impex;
	exports com.mynetpcb.core.capi.io;
	exports com.mynetpcb.core.capi.io.search;
	exports com.mynetpcb.core.capi.io.remote;
	exports com.mynetpcb.core.capi.io.remote.rest;
	exports com.mynetpcb.core.capi.text;
	exports com.mynetpcb.core.capi.text.font;
	exports com.mynetpcb.core.capi.text.glyph;
	exports com.mynetpcb.core.capi.layer;
	exports com.mynetpcb.core.capi.line;
	exports com.mynetpcb.core.capi.panel;
	exports com.mynetpcb.core.capi.pin;
	exports com.mynetpcb.core.capi.popup;	
	exports com.mynetpcb.core.capi.tree;
	exports com.mynetpcb.core.capi.undo;
	exports com.mynetpcb.core.pad;
	exports com.mynetpcb.core.pad.shape;
	exports com.mynetpcb.core.board;
	exports com.mynetpcb.core.board.shape;
	exports com.mynetpcb.core.dialog.config;
	exports com.mynetpcb.core.dialog.load;
	exports com.mynetpcb.core.dialog.print;
	exports com.mynetpcb.core.dialog.save;
	
	requires java.xml;
    requires java.xml.bind;
	requires  java.desktop; 
	requires  com.mynetpcb.d2;
	
	opens com.mynetpcb.core.capi.config to java.xml.bind;
}